// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5rYoBt0-qmAWRYqiZ8W3C8OmuCADcpIQ',
    appId: '1:535048283848:android:afde79f8ba34752bdc27fd',
    messagingSenderId: '535048283848',
    projectId: 'chatapp-3c1e9',
    databaseURL: 'https://chatapp-3c1e9-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-3c1e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU0fbCkRaA867CSOyqKp5DYntId0JmCHk',
    appId: '1:535048283848:ios:fa23e4895797d13cdc27fd',
    messagingSenderId: '535048283848',
    projectId: 'chatapp-3c1e9',
    databaseURL: 'https://chatapp-3c1e9-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-3c1e9.appspot.com',
    iosBundleId: 'com.example.whisper',
  );
}
